site_name: Learn ReactJS - Documentación
site_description: Documentación del curso de ReactJS
site_author: Facundo

theme:
  name: material
  language: es
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Inicio: index.md
  - Sesión 1 - Fundamentos:
      - Introducción: Session_1/Introducción.md
  - Sesión 2 - Formularios:
      - Formularios: Session_2/Formularios.md
      - Formularios No Controlados: Session_2/FormNoControl.md
      - Capítulo 3: Session_2/Capitulo_3.md
  - Sesión 3 - Hooks y API:
      - useEffect: Session_3/useEffect.md
      - Interfaces: Session_3/interface.md
      - API: Session_3/API.md
      - Gestión de Errores: Session_3/GesError.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search:
      lang: es
